# Generated by Django 3.2.9 on 2022-01-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20211221_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
        migrations.DeleteModel(
            name='NeighbourHood',
        ),
    ]
